# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e14b94a95955959bfefe9031fdb271db69d373476b34776e9ff79d6e243e3afe8aab877067aed4fd34aa0188879859a2e7dbb5e46dbde4eb55c2b31d07be89
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: 01be0ee76b5bd334fdd13cd4f6dacfe34cb6959a935896940b9f1b93b971d48cab2b31c86ac21565ae022b9815aad3b0fad66f5ee9da947d5edba6a42fabd4bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
